"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { HeartPulse, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Document } from "@/types";

export default function CertificatePage() {
  const [doc, setDoc] = useState<Document | null>(null);
  const params = useParams();

  useEffect(() => {
    const documents: Document[] = JSON.parse(
      localStorage.getItem("documents") || "[]"
    );
    const documentId = typeof params.id === "string" ? params.id : "";
    const foundDoc = documents.find((d) => d.id === documentId);
    if (foundDoc) {
      setDoc(foundDoc);
    }
  }, [params.id]);

  if (!doc) {
    return (
      <div className="flex h-screen items-center justify-center">
        <p>Loading certificate...</p>
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-gray-100 min-h-screen p-4 sm:p-8 flex items-center justify-center">
      <div className="w-full max-w-4xl mx-auto">
        <div className="flex justify-end gap-2 mb-4 print:hidden">
            <Button onClick={handlePrint} variant="outline">Print / Save PDF</Button>
            <Button onClick={() => window.history.back()}>Back to Document</Button>
        </div>
        <div className="bg-white p-8 sm:p-12 shadow-2xl rounded-lg border-4 border-primary/20" style={{ fontFamily: "'Times New Roman', serif" }}>
          <div className="border-2 border-secondary p-6 rounded-md">
            <header className="text-center mb-8">
              <div className="flex justify-center items-center gap-3 text-primary">
                <HeartPulse className="h-12 w-12" />
                <h1 className="text-4xl font-bold text-gray-800">MediSafe Pro</h1>
              </div>
              <p className="text-lg text-gray-500 mt-2">Official Health Record</p>
            </header>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-700 border-b-2 border-gray-200 pb-2 mb-4 flex items-center gap-2">
                <FileText />
                {doc.name}
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-4 text-lg">
                <p><strong>Document Type:</strong> {doc.type}</p>
                <p><strong>Upload Date:</strong> {new Date(doc.uploadDate).toLocaleDateString()}</p>
              </div>
            </section>
            
            <section className="mb-8">
               <h3 className="text-xl font-semibold text-gray-600 mb-2">AI-Generated Summary</h3>
               <p className="text-gray-700 italic bg-gray-50 p-4 rounded-md border-l-4 border-primary">
                {doc.summary}
               </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold text-gray-600 mb-2">Full Document Content</h3>
              <pre className="whitespace-pre-wrap font-serif text-gray-800 bg-gray-50 p-4 rounded-md border border-gray-200">
                {doc.content}
              </pre>
            </section>
            
            <footer className="mt-12 text-center">
                <p className="text-sm text-gray-400">
                    Generated by MediSafe Pro on {new Date().toLocaleDateString()}.
                </p>
                <p className="text-sm text-gray-400">
                    This document is a representation of a record stored securely in the MediSafe Pro system.
                </p>
            </footer>
          </div>
        </div>
      </div>
    </div>
  );
}
